### ISSUE TITLE
Error message in gulpfile.js on Windows

### ISSUE THREAD

**Issue by J3soon** [ramswaroop/photography#13]
If someone has encountered the error below when executing `gulp` on Windows.

    C:\path\to\photography>gulp
    [22:25:59] Using gulpfile C:\path\to\photography\gulpfile.js
    [22:25:59] Starting 'resize'...

    events.js:183
          throw er; // Unhandled 'error' event
          ^
    Error: Error: write EOF
        at finish (C:\path\to\photography\node_modules\gulp-gm\index.js:40:21)
        at gm.<anonymous> (C:\path\to\photography\node_modules\async\lib\async.js:485:30)
        at emitMany (events.js:147:13)
        at gm.emit (events.js:224:7)
        at gm.<anonymous> (C:\path\to\photography\node_modules\gm\lib\getters.js:70:16)
        at Socket.cb (C:\path\to\photography\node_modules\gm\lib\command.js:322:16)
        at Object.onceWrapper (events.js:315:30)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at onwriteError (_stream_writable.js:408:12)

Download [Graphicsmagick](http://www.graphicsmagick.org/), and change line 14, 19 in `gulpfile.js` to

    imageMagick: false

Then `gulp` can run without error.

    C:\path\to\photography>gulp
    [23:16:32] Using gulpfile C:\path\to\photography\gulpfile.js
    [23:16:32] Starting 'resize'...
    [23:16:32] Finished 'resize' after 26 ms
    [23:16:32] Starting 'del'...
    [23:16:32] Finished 'del' after 2.39 ms
    [23:16:32] Starting 'default'...
    [23:16:32] Finished 'default' after 22 μs

**Comment by J3soon** [comment]
I put the solution here, so if anyone encounters the same problem as I had, they can fix it quickly.

**Comment by somshot** [comment]
I did this but still can't get the gulp work. It is just not picking up new images.
