### ISSUE TITLE
Gulp auto-resize

### ISSUE THREAD

**Issue by nhatn1507** [ramswaroop/photography#7]
After using Terminal (MacOS) to navigate to the repo, I type $ gulp to resize the image inside "images" folder but the following error occurs. Could you please tell me why it happens and how to fix it?

Using gulpfile ~/Desktop/light/gulpfile.js
[06:07:28] Starting 'resize'...

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
    at finish (/Users/Lullaby/Desktop/light/node_modules/gulp-gm/index.js:40:21)
    at gm.<anonymous> (/Users/Lullaby/Desktop/light/node_modules/async/lib/async.js:485:30)
    at emitMany (events.js:146:13)
    at gm.emit (events.js:223:7)
    at gm.<anonymous> (/Users/Lullaby/Desktop/light/node_modules/gm/lib/getters.js:70:16)
    at cb (/Users/Lullaby/Desktop/light/node_modules/gm/lib/command.js:322:16)
    at ChildProcess.<anonymous> (/Users/Lullaby/Desktop/light/node_modules/gm/lib/command.js:232:9)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by nhatn1507** [comment]
In addition, the images (both full and thumb) don't load on my github page. I really can't tell the reason for this. Please take a look at both of them if you have time!
Thanks!
repo: https://github.com/nhatn1507/light
github page: https://nhatn1507.github.io/light/

**Comment by ramswaroop** [comment]
@nhatn1507 you have forked the repo to `light` and not to `photography` so you have to update the same in `_config.yml` file. See README.md for detailed instructions.

**Comment by nhatn1507** [comment]
Thanks. The photos show up now, but only if I put them in "fulls" folder. I try to use gulpfile to resize images that I put in "images", but the same error still comes up.

**Comment by ramswaroop** [comment]
Yes, you have to put the images to both of the folders to make the website function properly. And regarding the other error, I think ImageMagick isnt installed properly. Did you run `npm install`?
